spring.application.name=KDT_HACK

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=hb2zp0#49#
spring.mvc.favicon.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com //????? ?????? ????????
spring.mail.port=587 
spring.mail.username= //????? ??? ????????
spring.mail.password= //?????? ?? ?????
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret.key = *B5IO);rv5.u94_)Ps3N4oo{x!>17LE3gO1$Y}T%$cRDh9=T6C*rR),N;4vez40<
jwt.lifetime = 604800000
app.verification.expiration-minutes = 15